In [1]:
#import numpy as np
#import matplotlib.pyplot as plt
import pandas as pd

# datasetMLS_11_12 = pd.read_csv('Hackathon Files/Hackathon Raw Files/Trimmed Columns - Opta/MLS/MLS 2011-2012 trimmed.csv')
# datasetMLS_12_13 = pd.read_csv('Hackathon Files/Hackathon Raw Files/Trimmed Columns - Opta/MLS/MLS 2012-2013 trimmed.csv')
# datasetMLS_13_14 = pd.read_csv('Hackathon Files/Hackathon Raw Files/Trimmed Columns - Opta/MLS/MLS 2013-2014 trimmed.csv')
# datasetMLS_14_15 = pd.read_csv('Hackathon Files/Hackathon Raw Files/Trimmed Columns - Opta/MLS/MLS 2014-2015 trimmed.csv')
# datasetMLS_15_16 = pd.read_csv('Hackathon Files/Hackathon Raw Files/Trimmed Columns - Opta/MLS/MLS 2015-2016 trimmed.csv')
# datasetMLS_16_17 = pd.read_csv('Hackathon Files/Hackathon Raw Files/Trimmed Columns - Opta/MLS/MLS 2016-2017 trimmed.csv')
# datasetMLS_17_18 = pd.read_csv('Hackathon Files/Hackathon Raw Files/Trimmed Columns - Opta/MLS/MLS 2017-2018 trimmed.csv')
# datasetMLS_18_19 = pd.read_csv('Hackathon Files/Hackathon Raw Files/Trimmed Columns - Opta/MLS/MLS 2018-2019 trimmed.csv')


datasetMLS_11_12 = pd.read_csv('Hackathon Files/Hackathon Raw Files/Full Datasets - Opta/MLS/MLS 2011-2012.csv')
datasetMLS_12_13 = pd.read_csv('Hackathon Files/Hackathon Raw Files/Full Datasets - Opta/MLS/MLS 2012-2013.csv')
datasetMLS_13_14 = pd.read_csv('Hackathon Files/Hackathon Raw Files/Full Datasets - Opta/MLS/MLS 2013-2014.csv')
datasetMLS_14_15 = pd.read_csv('Hackathon Files/Hackathon Raw Files/Full Datasets - Opta/MLS/MLS 2014-2015.csv')
datasetMLS_15_16 = pd.read_csv('Hackathon Files/Hackathon Raw Files/Full Datasets - Opta/MLS/MLS 2015-2016.csv')
datasetMLS_16_17 = pd.read_csv('Hackathon Files/Hackathon Raw Files/Full Datasets - Opta/MLS/MLS 2016-2017.csv')
datasetMLS_17_18 = pd.read_csv('Hackathon Files/Hackathon Raw Files/Full Datasets - Opta/MLS/MLS 2017-2018.csv')
datasetMLS_18_19 = pd.read_csv('Hackathon Files/Hackathon Raw Files/Full Datasets - Opta/MLS/MLS 2018-2019.csv')
print('Done')

C:\Users\arshd\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (226) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\arshd\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (186,190,192,226,287) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\arshd\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (288) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\arshd\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (186,190,192,288) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\arshd\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (226,288,298) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\arshd\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (288,298) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)
C:\Users\arshd\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:2785: DtypeWarning: Columns (226,287,288,298) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

Done

In [3]:
def createRatingDataframe(sourceDf,playerDict):
    defObj = {'clubName':'','player_id':0, 'player':'', 'pass':0,'successfulPass':0, 'shot':0, 
              'cross':0, 'through_ball':0,'dribble':0, 'assist':0,'blockpass':0,'foulConceded':0,
              'goal':0, 'ttime':0,'yellow_card':0,'red_card':0,'tackles':0,'tackleSuccess':0,'blocks':0,'saves':0}
    data = sourceDf.groupby('game_id')
    for key, item in data:
        matchObj = data.get_group(key)
        matchObj = matchObj.dropna(subset=['player_id'])
        ctr=0
        for idx,rowObj in matchObj.iterrows():
            playerId = (rowObj['player_id'])
            if playerId == '':
                continue;
            else:
                playerId = int(playerId)
            if playerId in playerDict:
                playerObj = playerDict[(playerId)]
            else:
                playerObj = defObj.copy()

            if playerObj['player_id'] == 0:
                playerObj['player_id'] = playerId
            if playerObj['player'] == '':
                playerObj['player'] = rowObj['player']
            playerObj['clubName'] = rowObj['team']
            event_id = rowObj['event_type_id']
            if event_id == 1:
                playerObj['pass'] += 1
                if(rowObj['outcome'])==1:
                    playerObj['successfulPass'] += 1
                if rowObj['cross'] == 1:
                    playerObj['cross']+=1
                if rowObj['assist'] == 1:
                    playerObj['assist']+=1
                if rowObj['through_ball']==1:
                    playerObj['through_ball']+=1
            elif event_id in[13,16,15,14]:
                playerObj['shot']+=1
                if event_id == 16:
                    playerObj['goal']+=1
            elif event_id == 3 and rowObj['outcome'] == 1:
                playerObj['dribble']+=1
            elif event_id == 4 and rowObj['outcome'] == 0:
                playerObj['foulConceded']+=1
            elif event_id==7:
                playerObj['tackles']+=1
                if(rowObj['outcome'])==1:
                    playerObj['tackleSuccess'] += 1
            elif event_id==10:
                if(rowObj['def_block'])==1:
                    playerObj['blocks'] += 1
                else:
                    playerObj['saves'] += 1
            elif event_id == 17:
                if rowObj['yellow_card']==1:
                    playerObj['yellow_card']+=1
                if rowObj['second_yellow']==1 or rowObj['red_card']==1 :
                    playerObj['red_card']+=1
            playerDict[playerId] = playerObj      
    return playerDict
print('done')

done

In [4]:
df1 = pd.DataFrame(datasetMLS_11_12)

df3 = pd.DataFrame(datasetMLS_13_14)
df4 = pd.DataFrame(datasetMLS_14_15)
df5 = pd.DataFrame(datasetMLS_15_16)
df6 = pd.DataFrame(datasetMLS_16_17)
df7 = pd.DataFrame(datasetMLS_17_18)
df8 = pd.DataFrame(datasetMLS_18_19)



playerDict = {}
playerDict = createRatingDataframe(df1,playerDict)
df2 = pd.DataFrame(datasetMLS_12_13)
playerDict = createRatingDataframe(df2,playerDict)
playerDict = createRatingDataframe(df3,playerDict)
playerDict = createRatingDataframe(df4,playerDict)
playerDict = createRatingDataframe(df5,playerDict)
playerDict = createRatingDataframe(df6,playerDict)
playerDict = createRatingDataframe(df7,playerDict)
playerDict = createRatingDataframe(df8,playerDict)

myArr=[]
for key, value in playerDict.items():
    myArr.append(value)
dframe=pd.DataFrame(myArr)
dframe

,assist,blockpass,blocks,clubName,cross,dribble,foulConceded,goal,pass,player,player_id,red_card,saves,shot,successfulPass,tackleSuccess,tackles,through_ball,ttime,yellow_card
0,22,0,145,FC Dallas,4,35,173,17,7358,Matt Hedges,110592,0,0,105,6185,275,354,2,0,28
1,3,0,0,Houston Dynamo,2,2,3,0,108,Chandler Hoffman,110593,0,0,6,96,4,5,0,0,1
2,0,0,4,New York Red Bulls,0,4,8,2,190,Gideon Baah,160396,0,0,8,137,12,18,0,0,0
3,23,0,0,Philadelphia Union,53,43,31,7,438,Antoine Hoppenot,110595,0,0,41,281,22,31,3,0,5
4,6,0,38,Houston Dynamo,14,11,57,3,1901,Raul Rodriguez,90116,1,0,26,1475,65,89,1,0,10
5,1,0,14,Orlando City SC,6,10,6,1,530,Amro Tarek Abdel-Aziz,212993,0,0,5,401,17,21,0,0,1
6,1,0,0,Chicago Fire,4,4,8,1,96,Hunter Jumper,110601,0,0,2,63,8,9,0,0,1
7,25,0,5,Atlanta United FC,51,10,33,1,1225,Chris McCann,20491,0,0,19,1002,26,36,1,0,4
8,43,0,19,Los Angeles Football Club,42,31,56,2,2136,Calum Mallace,110606,1,0,51,1788,72,95,6,0,9
9,55,0,5,Montreal Impact,55,27,48,22,989,Didier Drogba,12303,1,0,151,559,18,23,4,0,7
10,70,0,5,D.C. United,43,111,107,33,1927,Darren Mattocks,110608,2,0,249,1377,66,83,11,0,14
11,1,0,0,New York Red Bulls,0,0,0,0,648,Ryan Meara,110609,0,85,0,392,1,1,0,0,2
12,5,0,18,LA Galaxy,6,3,27,0,1302,Tommy Meyer,110610,0,0,3,1012,31,39,0,0,0
13,61,0,43,Vancouver Whitecaps FC,28,40,251,4,6163,Matías Laba,86035,5,0,52,5122,466,614,14,0,30
14,17,0,0,Montreal Impact,40,27,14,1,597,Alejandro Silva,120760,0,0,19,446,27,40,4,0,2
15,1,0,0,San Jose Earthquakes,0,0,0,0,10,Mawxell Griffin,106518,0,0,0,9,0,0,0,0,0
16,0,0,0,New England Revolution,1,1,0,0,57,NaN,110615,0,0,1,49,2,5,0,0,0
17,3,0,19,Vancouver Whitecaps FC,4,3,23,1,863,Carlyle Mitchell,106520,0,0,11,697,27,35,0,0,5
18,0,0,0,Philadelphia Union,0,0,1,0,1,Morgan Langley,106521,0,0,0,1,0,0,0,0,0
19,9,0,5,Real Salt Lake,6,15,56,1,1445,Yordany Alvarez,106522,2,0,17,1222,61,77,2,0,10
20,246,0,22,New England Revolution,529,175,208,29,6012,Kelyn Rowe,110619,0,0,360,4159,271,346,34,0,17
21,2,0,0,Vancouver Whitecaps FC,0,3,1,0,2243,Brian Rowe,110620,0,220,0,1416,1,2,0,0,0
22,1,0,0,San Jose Earthquakes,3,2,0,0,53,Billy Schuler,110622,0,0,4,45,0,0,0,0,0
23,1,0,2,Chicago Fire,0,8,20,0,326,Mohammed Adams,200735,1,0,0,276,25,41,1,0,3
24,159,0,3,Real Salt Lake,223,63,92,32,3434,Luis Silva,110624,0,0,231,2522,69,96,37,0,11
25,12,0,0,FC Dallas,23,7,4,0,226,Rolando Escobar,53281,0,0,7,162,10,13,3,0,0
26,10,0,0,D.C. United,7,0,17,1,339,Casey Townsend,110627,0,0,21,223,5,6,0,0,4
27,70,0,15,Portland Timbers,419,86,107,5,4514,Jorge Villafaña,45092,1,0,78,3347,215,245,6,0,10
28,11,0,2,Columbus Crew SC,31,0,7,0,256,NaN,110629,0,0,5,189,7,8,0,0,1
29,2,0,0,LA Galaxy,3,4,12,0,443,Kenney Walker,110630,0,0,3,386,22,26,4,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1548,43,0,0,Los Angeles Football Club,18,41,25,5,656,Marcos Ureña,77755,0,0,67,486,6,13,5,0,3
1549,52,0,2,Portland Timbers,102,26,64,1,1684,David Guzmán,77756,0,0,47,1349,58,83,2,0,12
1550,1,0,0,Chicago Fire,1,1,2,0,21,Guillermo Franco,28608,1,0,1,14,2,2,0,0,0
1551,32,0,7,Atlanta United FC,67,14,32,0,1667,Mark Bloom,118721,0,0,12,1215,84,103,0,0,3
1552,1,0,0,New York Red Bulls,11,6,16,1,181,Josué Martinez,77765,0,0,15,129,9,13,2,0,1
1553,19,0,0,Orlando City SC,30,13,33,5,556,Adrian Winter,66209,1,0,28,403,20,31,0,0,3
1554,52,0,1,Atlanta United FC,61,65,43,17,1153,Héctor Villalba,122828,0,0,118,804,35,58,3,0,6
1555,2,0,23,New York Red Bulls,2,3,41,1,1316,Matt Miazga,163793,3,0,27,1008,65,80,2,0,8
1556,5,0,0,Toronto FC,0,1,2,0,3591,Clinton Irwin,118738,0,360,0,2137,0,2,0,0,6
1557,3,0,0,Minnesota United FC,34,8,10,0,388,Edwin Gomez,159702,0,0,16,279,17,25,1,0,3
1558,23,0,5,Real Salt Lake,2,30,84,1,1840,Stephen Obayan Sunday,43684,0,0,16,1593,85,119,1,0,15
1559,1,0,0,New York Red Bulls,3,0,1,0,31,NaN,110554,0,0,0,24,2,2,0,0,0
1560,60,0,14,Orlando City SC,113,52,98,1,2659,RJ Allen,110557,1,0,19,2052,107,136,5,0,17
1561,1,0,35,New York City FC,5,25,52,3,3327,Alexander Callens,159710,1,0,24,2861,58,76,0,0,7
1562,71,0,6,Colorado Rapids,77,42,94,18,1930,Kevin Doyle,20450,0,0,168,1362,48,64,6,0,14
1563,14,0,7,LA Galaxy,26,12,44,1,1161,João Pedro Almeida Machado,159716,0,0,28,932,33,55,0,0,8
1564,9,0,2,Sporting Kansas City,11,2,15,0,323,Jordi Quintillà,106471,0,0,11,262,16,17,1,0,1
1565,11,0,30,Philadelphia Union,1,12,41,4,2130,Austin Berry,110568,0,0,30,1729,81,95,0,0,6
1566,52,0,3,Philadelphia Union,102,56,36,9,3493,Vincent Nogueira,45033,0,0,98,2926,59,77,16,0,8
1567,7,0,19,Columbus Crew SC,7,16,19,0,1573,Nicolai Naess,114295,0,0,14,1341,40,57,3,0,1
1568,39,0,1,Houston Dynamo,44,29,34,4,937,Tony Cascio,110572,1,0,75,728,38,43,5,0,2
1569,41,0,23,Philadelphia Union,56,78,124,5,3946,Warren Creavalle,110575,2,0,41,3143,243,299,8,0,19
1570,166,0,30,D.C. United,323,172,136,17,6590,Nick DeLeon,110580,0,0,231,5206,211,267,24,0,16
1571,143,0,4,Minnesota United FC,357,88,123,36,3204,Ethan Finlay,110583,1,0,218,2251,133,159,11,0,10
1572,0,0,0,LA Galaxy,0,1,1,0,1727,Jaime Penedo,28665,0,188,0,986,1,2,0,0,2
1573,4,0,14,LA Galaxy,16,5,40,0,1083,Rafael Garcia,110586,0,0,5,889,28,47,0,0,4
1574,3,0,0,San Jose Earthquakes,21,7,3,0,97,Sam Garza,110587,0,0,7,62,7,11,2,0,1
1575,6,0,0,LA Galaxy,20,2,13,0,359,Bryan Gaul,110588,0,0,4,268,14,18,0,0,3
1576,4,0,9,Columbus Crew SC,1,3,25,0,701,Kevan George,110589,0,0,9,604,27,32,1,0,8
1577,0,0,0,Atlanta United FC,0,0,0,0,23,Paul Christensen,442453,0,1,0,5,0,0,0,0,0

In [5]:
dframe.to_csv('new.csv', sep=',')

an=pd.read_csv('new.csv')
an

,Unnamed: 0,assist,blockpass,blocks,clubName,cross,dribble,foulConceded,goal,pass,...,player_id,red_card,saves,shot,successfulPass,tackleSuccess,tackles,through_ball,ttime,yellow_card
0,0,22,0,145,FC Dallas,4,35,173,17,7358,...,110592,0,0,105,6185,275,354,2,0,28
1,1,3,0,0,Houston Dynamo,2,2,3,0,108,...,110593,0,0,6,96,4,5,0,0,1
2,2,0,0,4,New York Red Bulls,0,4,8,2,190,...,160396,0,0,8,137,12,18,0,0,0
3,3,23,0,0,Philadelphia Union,53,43,31,7,438,...,110595,0,0,41,281,22,31,3,0,5
4,4,6,0,38,Houston Dynamo,14,11,57,3,1901,...,90116,1,0,26,1475,65,89,1,0,10
5,5,1,0,14,Orlando City SC,6,10,6,1,530,...,212993,0,0,5,401,17,21,0,0,1
6,6,1,0,0,Chicago Fire,4,4,8,1,96,...,110601,0,0,2,63,8,9,0,0,1
7,7,25,0,5,Atlanta United FC,51,10,33,1,1225,...,20491,0,0,19,1002,26,36,1,0,4
8,8,43,0,19,Los Angeles Football Club,42,31,56,2,2136,...,110606,1,0,51,1788,72,95,6,0,9
9,9,55,0,5,Montreal Impact,55,27,48,22,989,...,12303,1,0,151,559,18,23,4,0,7
10,10,70,0,5,D.C. United,43,111,107,33,1927,...,110608,2,0,249,1377,66,83,11,0,14
11,11,1,0,0,New York Red Bulls,0,0,0,0,648,...,110609,0,85,0,392,1,1,0,0,2
12,12,5,0,18,LA Galaxy,6,3,27,0,1302,...,110610,0,0,3,1012,31,39,0,0,0
13,13,61,0,43,Vancouver Whitecaps FC,28,40,251,4,6163,...,86035,5,0,52,5122,466,614,14,0,30
14,14,17,0,0,Montreal Impact,40,27,14,1,597,...,120760,0,0,19,446,27,40,4,0,2
15,15,1,0,0,San Jose Earthquakes,0,0,0,0,10,...,106518,0,0,0,9,0,0,0,0,0
16,16,0,0,0,New England Revolution,1,1,0,0,57,...,110615,0,0,1,49,2,5,0,0,0
17,17,3,0,19,Vancouver Whitecaps FC,4,3,23,1,863,...,106520,0,0,11,697,27,35,0,0,5
18,18,0,0,0,Philadelphia Union,0,0,1,0,1,...,106521,0,0,0,1,0,0,0,0,0
19,19,9,0,5,Real Salt Lake,6,15,56,1,1445,...,106522,2,0,17,1222,61,77,2,0,10
20,20,246,0,22,New England Revolution,529,175,208,29,6012,...,110619,0,0,360,4159,271,346,34,0,17
21,21,2,0,0,Vancouver Whitecaps FC,0,3,1,0,2243,...,110620,0,220,0,1416,1,2,0,0,0
22,22,1,0,0,San Jose Earthquakes,3,2,0,0,53,...,110622,0,0,4,45,0,0,0,0,0
23,23,1,0,2,Chicago Fire,0,8,20,0,326,...,200735,1,0,0,276,25,41,1,0,3
24,24,159,0,3,Real Salt Lake,223,63,92,32,3434,...,110624,0,0,231,2522,69,96,37,0,11
25,25,12,0,0,FC Dallas,23,7,4,0,226,...,53281,0,0,7,162,10,13,3,0,0
26,26,10,0,0,D.C. United,7,0,17,1,339,...,110627,0,0,21,223,5,6,0,0,4
27,27,70,0,15,Portland Timbers,419,86,107,5,4514,...,45092,1,0,78,3347,215,245,6,0,10
28,28,11,0,2,Columbus Crew SC,31,0,7,0,256,...,110629,0,0,5,189,7,8,0,0,1
29,29,2,0,0,LA Galaxy,3,4,12,0,443,...,110630,0,0,3,386,22,26,4,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1548,1548,43,0,0,Los Angeles Football Club,18,41,25,5,656,...,77755,0,0,67,486,6,13,5,0,3
1549,1549,52,0,2,Portland Timbers,102,26,64,1,1684,...,77756,0,0,47,1349,58,83,2,0,12
1550,1550,1,0,0,Chicago Fire,1,1,2,0,21,...,28608,1,0,1,14,2,2,0,0,0
1551,1551,32,0,7,Atlanta United FC,67,14,32,0,1667,...,118721,0,0,12,1215,84,103,0,0,3
1552,1552,1,0,0,New York Red Bulls,11,6,16,1,181,...,77765,0,0,15,129,9,13,2,0,1
1553,1553,19,0,0,Orlando City SC,30,13,33,5,556,...,66209,1,0,28,403,20,31,0,0,3
1554,1554,52,0,1,Atlanta United FC,61,65,43,17,1153,...,122828,0,0,118,804,35,58,3,0,6
1555,1555,2,0,23,New York Red Bulls,2,3,41,1,1316,...,163793,3,0,27,1008,65,80,2,0,8
1556,1556,5,0,0,Toronto FC,0,1,2,0,3591,...,118738,0,360,0,2137,0,2,0,0,6
1557,1557,3,0,0,Minnesota United FC,34,8,10,0,388,...,159702,0,0,16,279,17,25,1,0,3
1558,1558,23,0,5,Real Salt Lake,2,30,84,1,1840,...,43684,0,0,16,1593,85,119,1,0,15
1559,1559,1,0,0,New York Red Bulls,3,0,1,0,31,...,110554,0,0,0,24,2,2,0,0,0
1560,1560,60,0,14,Orlando City SC,113,52,98,1,2659,...,110557,1,0,19,2052,107,136,5,0,17
1561,1561,1,0,35,New York City FC,5,25,52,3,3327,...,159710,1,0,24,2861,58,76,0,0,7
1562,1562,71,0,6,Colorado Rapids,77,42,94,18,1930,...,20450,0,0,168,1362,48,64,6,0,14
1563,1563,14,0,7,LA Galaxy,26,12,44,1,1161,...,159716,0,0,28,932,33,55,0,0,8
1564,1564,9,0,2,Sporting Kansas City,11,2,15,0,323,...,106471,0,0,11,262,16,17,1,0,1
1565,1565,11,0,30,Philadelphia Union,1,12,41,4,2130,...,110568,0,0,30,1729,81,95,0,0,6
1566,1566,52,0,3,Philadelphia Union,102,56,36,9,3493,...,45033,0,0,98,2926,59,77,16,0,8
1567,1567,7,0,19,Columbus Crew SC,7,16,19,0,1573,...,114295,0,0,14,1341,40,57,3,0,1
1568,1568,39,0,1,Houston Dynamo,44,29,34,4,937,...,110572,1,0,75,728,38,43,5,0,2
1569,1569,41,0,23,Philadelphia Union,56,78,124,5,3946,...,110575,2,0,41,3143,243,299,8,0,19
1570,1570,166,0,30,D.C. United,323,172,136,17,6590,...,110580,0,0,231,5206,211,267,24,0,16
1571,1571,143,0,4,Minnesota United FC,357,88,123,36,3204,...,110583,1,0,218,2251,133,159,11,0,10
1572,1572,0,0,0,LA Galaxy,0,1,1,0,1727,...,28665,0,188,0,986,1,2,0,0,2
1573,1573,4,0,14,LA Galaxy,16,5,40,0,1083,...,110586,0,0,5,889,28,47,0,0,4
1574,1574,3,0,0,San Jose Earthquakes,21,7,3,0,97,...,110587,0,0,7,62,7,11,2,0,1
1575,1575,6,0,0,LA Galaxy,20,2,13,0,359,...,110588,0,0,4,268,14,18,0,0,3
1576,1576,4,0,9,Columbus Crew SC,1,3,25,0,701,...,110589,0,0,9,604,27,32,1,0,8
1577,1577,0,0,0,Atlanta United FC,0,0,0,0,23,...,442453,0,1,0,5,0,0,0,0,0

In [6]:
def createPenaltyAnalysisDataframe(sourceDf,playerDict):
    defObj = {'clubName':'','player_id':0, 'player':'', 'low_left':0,'high_left':0, 'low_centre':0, 
              'high_centre':0, 'low_right':0,'high_right':0,'close_left':0,'close_right':0,
              'close_high':0,'close_left_and_high':0,'saves':0,'close_right_and_high':0}
    data = sourceDf.groupby('game_id')
    for key, item in data:
        matchObj = data.get_group(key)
        matchObj = matchObj.dropna(subset=['player_id'])
        ctr=0
        for idx,rowObj in matchObj.iterrows():
            playerId = (rowObj['player_id'])
            if playerId == '':
                continue;
            else:
                playerId = int(playerId)
            if playerId in playerDict:
                playerObj = playerDict[(playerId)]
            else:
                playerObj = defObj.copy()

            if playerObj['player_id'] == 0:
                playerObj['player_id'] = playerId
            if playerObj['player'] == '':
                playerObj['player'] = rowObj['player']
            playerObj['clubName'] = rowObj['team']
            event_id = rowObj['event_type_id']
            if event_id in[13,16,15,14]:

                if rowObj['low_left'] == 1:
                    playerObj['low_left']+=1
                if rowObj['high_left'] == 1:
                    playerObj['high_left']+=1
                if rowObj['low_centre'] == 1:
                    playerObj['low_centre']+=1
                if rowObj['high_centre'] == 1:
                    playerObj['high_centre']+=1
                if rowObj['low_right'] == 1:
                    playerObj['low_right']+=1
                if rowObj['high_right'] == 1:
                    playerObj['high_right']+=1
                if rowObj['close_left'] == 1:
                    playerObj['close_left']+=1
                if rowObj['close_right'] == 1:
                    playerObj['close_right']+=1
                if rowObj['close_high'] == 1:
                    playerObj['close_high']+=1
                if rowObj['close_left_and_high'] == 1:
                    playerObj['close_left_and_high']+=1
                if rowObj['close_right_and_high'] == 1:
                    playerObj['close_right_and_high']+=1
                
            playerDict[playerId] = playerObj      
    return playerDict
print('done')

done

In [7]:
playerDictRat = {}
playerDictRat = createPenaltyAnalysisDataframe(df1,playerDictRat)
playerDictRat = createPenaltyAnalysisDataframe(df2,playerDictRat)
playerDictRat = createPenaltyAnalysisDataframe(df3,playerDictRat)
playerDictRat = createPenaltyAnalysisDataframe(df4,playerDictRat)
playerDictRat = createPenaltyAnalysisDataframe(df5,playerDictRat)
playerDictRat = createPenaltyAnalysisDataframe(df6,playerDictRat)
playerDictRat = createPenaltyAnalysisDataframe(df7,playerDictRat)
playerDictRat = createPenaltyAnalysisDataframe(df8,playerDictRat)

myArr=[]
for key, value in playerDictRat.items():
    myArr.append(value)
dframeRating=pd.DataFrame(myArr)
dframeRating

,close_high,close_left,close_left_and_high,close_right,close_right_and_high,clubName,high_centre,high_left,high_right,low_centre,low_left,low_right,player,player_id,saves
0,3,3,1,4,0,FC Dallas,9,4,6,9,10,4,Matt Hedges,110592,0
1,0,2,0,0,0,Houston Dynamo,0,0,0,1,1,0,Chandler Hoffman,110593,0
2,0,1,0,0,0,New York Red Bulls,1,0,0,0,1,1,Gideon Baah,160396,0
3,2,1,0,1,1,Philadelphia Union,1,3,4,6,3,4,Antoine Hoppenot,110595,0
4,2,1,0,1,1,Houston Dynamo,2,0,1,1,3,1,Raul Rodriguez,90116,0
5,0,0,0,1,0,Orlando City SC,1,0,0,1,2,0,Amro Tarek Abdel-Aziz,212993,0
6,0,0,0,0,0,Chicago Fire,0,0,0,0,0,1,Hunter Jumper,110601,0
7,0,1,0,0,0,Atlanta United FC,3,0,0,1,0,0,Chris McCann,20491,0
8,0,2,0,0,0,Los Angeles Football Club,1,2,7,3,2,2,Calum Mallace,110606,0
9,7,4,4,6,3,Montreal Impact,8,7,14,19,16,10,Didier Drogba,12303,0
10,6,15,1,12,2,D.C. United,8,7,17,33,19,32,Darren Mattocks,110608,0
11,0,0,0,0,0,New York Red Bulls,0,0,0,0,0,0,Ryan Meara,110609,0
12,0,0,0,0,0,LA Galaxy,0,0,0,0,0,0,Tommy Meyer,110610,0
13,1,3,0,0,0,Vancouver Whitecaps FC,0,3,5,5,4,4,Matías Laba,86035,0
14,0,0,0,0,0,Montreal Impact,0,0,2,3,0,3,Alejandro Silva,120760,0
15,0,0,0,0,0,San Jose Earthquakes,0,0,0,0,0,0,Mawxell Griffin,106518,0
16,0,0,0,0,0,New England Revolution,0,0,0,0,1,0,NaN,110615,0
17,0,0,0,0,0,Vancouver Whitecaps FC,0,3,2,1,0,0,Carlyle Mitchell,106520,0
18,0,0,0,0,0,Philadelphia Union,0,0,0,0,0,0,Morgan Langley,106521,0
19,0,0,0,2,0,Real Salt Lake,0,1,3,3,2,0,Yordany Alvarez,106522,0
20,10,22,3,15,4,New England Revolution,11,20,36,37,25,29,Kelyn Rowe,110619,0
21,0,0,0,0,0,Vancouver Whitecaps FC,0,0,0,0,0,0,Brian Rowe,110620,0
22,0,0,0,0,0,San Jose Earthquakes,0,0,2,1,0,0,Billy Schuler,110622,0
23,0,0,0,0,0,Chicago Fire,0,0,0,0,0,0,Mohammed Adams,200735,0
24,6,14,0,14,4,Real Salt Lake,7,13,13,28,20,24,Luis Silva,110624,0
25,1,0,0,0,0,FC Dallas,0,0,0,3,0,0,Rolando Escobar,53281,0
26,0,1,0,1,0,D.C. United,2,1,4,1,3,2,Casey Townsend,110627,0
27,0,4,2,1,0,Portland Timbers,1,4,5,3,9,9,Jorge Villafaña,45092,0
28,0,0,0,1,0,Columbus Crew SC,0,0,0,0,0,0,NaN,110629,0
29,0,0,0,0,0,LA Galaxy,0,0,0,0,1,0,Kenney Walker,110630,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1548,2,3,1,5,0,Los Angeles Football Club,0,1,1,10,10,10,Marcos Ureña,77755,0
1549,0,5,1,2,1,Portland Timbers,1,0,3,3,2,4,David Guzmán,77756,0
1550,0,0,0,0,0,Chicago Fire,0,0,1,0,0,0,Guillermo Franco,28608,0
1551,0,0,0,1,0,Atlanta United FC,0,0,2,2,1,1,Mark Bloom,118721,0
1552,0,0,0,3,0,New York Red Bulls,1,0,2,3,1,1,Josué Martinez,77765,0
1553,1,1,0,0,0,Orlando City SC,2,1,0,3,2,5,Adrian Winter,66209,0
1554,2,6,0,12,1,Atlanta United FC,2,7,7,22,12,14,Héctor Villalba,122828,0
1555,2,2,1,1,0,New York Red Bulls,2,0,0,2,5,0,Matt Miazga,163793,0
1556,0,0,0,0,0,Toronto FC,0,0,0,0,0,0,Clinton Irwin,118738,0
1557,1,1,0,0,0,Minnesota United FC,0,1,0,4,1,0,Edwin Gomez,159702,0
1558,3,1,0,0,0,Real Salt Lake,1,1,1,0,0,0,Stephen Obayan Sunday,43684,0
1559,0,0,0,0,0,New York Red Bulls,0,0,0,0,0,0,NaN,110554,0
1560,0,1,0,1,0,Orlando City SC,1,1,0,0,1,2,RJ Allen,110557,0
1561,0,1,0,3,0,New York City FC,0,0,0,3,0,1,Alexander Callens,159710,0
1562,3,12,2,9,1,Colorado Rapids,4,7,4,18,12,10,Kevin Doyle,20450,0
1563,0,0,0,0,1,LA Galaxy,1,0,5,1,1,1,João Pedro Almeida Machado,159716,0
1564,0,0,0,2,1,Sporting Kansas City,0,1,1,1,0,1,Jordi Quintillà,106471,0
1565,0,2,0,2,0,Philadelphia Union,1,1,2,2,4,2,Austin Berry,110568,0
1566,3,6,0,7,3,Philadelphia Union,0,3,12,5,10,4,Vincent Nogueira,45033,0
1567,0,0,0,0,0,Columbus Crew SC,0,1,1,0,2,1,Nicolai Naess,114295,0
1568,4,5,0,0,0,Houston Dynamo,1,2,6,7,10,5,Tony Cascio,110572,0
1569,0,2,0,0,1,Philadelphia Union,1,7,1,4,2,3,Warren Creavalle,110575,0
1570,4,13,1,8,1,D.C. United,7,12,22,22,28,16,Nick DeLeon,110580,0
1571,2,6,2,10,3,Minnesota United FC,7,8,9,38,24,18,Ethan Finlay,110583,0
1572,0,0,0,0,0,LA Galaxy,0,0,0,0,0,0,Jaime Penedo,28665,0
1573,0,0,0,0,0,LA Galaxy,1,0,0,1,0,1,Rafael Garcia,110586,0
1574,1,2,0,0,0,San Jose Earthquakes,0,0,0,1,0,0,Sam Garza,110587,0
1575,0,0,0,0,0,LA Galaxy,0,0,0,1,0,1,Bryan Gaul,110588,0
1576,0,1,0,1,0,Columbus Crew SC,0,1,2,0,0,1,Kevan George,110589,0
1577,0,0,0,0,0,Atlanta United FC,0,0,0,0,0,0,Paul Christensen,442453,0

In [8]:
dframeRating.to_csv('penalty.csv', sep=',')

an=pd.read_csv('penalty.csv')
an

,Unnamed: 0,close_high,close_left,close_left_and_high,close_right,close_right_and_high,clubName,high_centre,high_left,high_right,low_centre,low_left,low_right,player,player_id,saves
0,0,3,3,1,4,0,FC Dallas,9,4,6,9,10,4,Matt Hedges,110592,0
1,1,0,2,0,0,0,Houston Dynamo,0,0,0,1,1,0,Chandler Hoffman,110593,0
2,2,0,1,0,0,0,New York Red Bulls,1,0,0,0,1,1,Gideon Baah,160396,0
3,3,2,1,0,1,1,Philadelphia Union,1,3,4,6,3,4,Antoine Hoppenot,110595,0
4,4,2,1,0,1,1,Houston Dynamo,2,0,1,1,3,1,Raul Rodriguez,90116,0
5,5,0,0,0,1,0,Orlando City SC,1,0,0,1,2,0,Amro Tarek Abdel-Aziz,212993,0
6,6,0,0,0,0,0,Chicago Fire,0,0,0,0,0,1,Hunter Jumper,110601,0
7,7,0,1,0,0,0,Atlanta United FC,3,0,0,1,0,0,Chris McCann,20491,0
8,8,0,2,0,0,0,Los Angeles Football Club,1,2,7,3,2,2,Calum Mallace,110606,0
9,9,7,4,4,6,3,Montreal Impact,8,7,14,19,16,10,Didier Drogba,12303,0
10,10,6,15,1,12,2,D.C. United,8,7,17,33,19,32,Darren Mattocks,110608,0
11,11,0,0,0,0,0,New York Red Bulls,0,0,0,0,0,0,Ryan Meara,110609,0
12,12,0,0,0,0,0,LA Galaxy,0,0,0,0,0,0,Tommy Meyer,110610,0
13,13,1,3,0,0,0,Vancouver Whitecaps FC,0,3,5,5,4,4,Matías Laba,86035,0
14,14,0,0,0,0,0,Montreal Impact,0,0,2,3,0,3,Alejandro Silva,120760,0
15,15,0,0,0,0,0,San Jose Earthquakes,0,0,0,0,0,0,Mawxell Griffin,106518,0
16,16,0,0,0,0,0,New England Revolution,0,0,0,0,1,0,NaN,110615,0
17,17,0,0,0,0,0,Vancouver Whitecaps FC,0,3,2,1,0,0,Carlyle Mitchell,106520,0
18,18,0,0,0,0,0,Philadelphia Union,0,0,0,0,0,0,Morgan Langley,106521,0
19,19,0,0,0,2,0,Real Salt Lake,0,1,3,3,2,0,Yordany Alvarez,106522,0
20,20,10,22,3,15,4,New England Revolution,11,20,36,37,25,29,Kelyn Rowe,110619,0
21,21,0,0,0,0,0,Vancouver Whitecaps FC,0,0,0,0,0,0,Brian Rowe,110620,0
22,22,0,0,0,0,0,San Jose Earthquakes,0,0,2,1,0,0,Billy Schuler,110622,0
23,23,0,0,0,0,0,Chicago Fire,0,0,0,0,0,0,Mohammed Adams,200735,0
24,24,6,14,0,14,4,Real Salt Lake,7,13,13,28,20,24,Luis Silva,110624,0
25,25,1,0,0,0,0,FC Dallas,0,0,0,3,0,0,Rolando Escobar,53281,0
26,26,0,1,0,1,0,D.C. United,2,1,4,1,3,2,Casey Townsend,110627,0
27,27,0,4,2,1,0,Portland Timbers,1,4,5,3,9,9,Jorge Villafaña,45092,0
28,28,0,0,0,1,0,Columbus Crew SC,0,0,0,0,0,0,NaN,110629,0
29,29,0,0,0,0,0,LA Galaxy,0,0,0,0,1,0,Kenney Walker,110630,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1548,1548,2,3,1,5,0,Los Angeles Football Club,0,1,1,10,10,10,Marcos Ureña,77755,0
1549,1549,0,5,1,2,1,Portland Timbers,1,0,3,3,2,4,David Guzmán,77756,0
1550,1550,0,0,0,0,0,Chicago Fire,0,0,1,0,0,0,Guillermo Franco,28608,0
1551,1551,0,0,0,1,0,Atlanta United FC,0,0,2,2,1,1,Mark Bloom,118721,0
1552,1552,0,0,0,3,0,New York Red Bulls,1,0,2,3,1,1,Josué Martinez,77765,0
1553,1553,1,1,0,0,0,Orlando City SC,2,1,0,3,2,5,Adrian Winter,66209,0
1554,1554,2,6,0,12,1,Atlanta United FC,2,7,7,22,12,14,Héctor Villalba,122828,0
1555,1555,2,2,1,1,0,New York Red Bulls,2,0,0,2,5,0,Matt Miazga,163793,0
1556,1556,0,0,0,0,0,Toronto FC,0,0,0,0,0,0,Clinton Irwin,118738,0
1557,1557,1,1,0,0,0,Minnesota United FC,0,1,0,4,1,0,Edwin Gomez,159702,0
1558,1558,3,1,0,0,0,Real Salt Lake,1,1,1,0,0,0,Stephen Obayan Sunday,43684,0
1559,1559,0,0,0,0,0,New York Red Bulls,0,0,0,0,0,0,NaN,110554,0
1560,1560,0,1,0,1,0,Orlando City SC,1,1,0,0,1,2,RJ Allen,110557,0
1561,1561,0,1,0,3,0,New York City FC,0,0,0,3,0,1,Alexander Callens,159710,0
1562,1562,3,12,2,9,1,Colorado Rapids,4,7,4,18,12,10,Kevin Doyle,20450,0
1563,1563,0,0,0,0,1,LA Galaxy,1,0,5,1,1,1,João Pedro Almeida Machado,159716,0
1564,1564,0,0,0,2,1,Sporting Kansas City,0,1,1,1,0,1,Jordi Quintillà,106471,0
1565,1565,0,2,0,2,0,Philadelphia Union,1,1,2,2,4,2,Austin Berry,110568,0
1566,1566,3,6,0,7,3,Philadelphia Union,0,3,12,5,10,4,Vincent Nogueira,45033,0
1567,1567,0,0,0,0,0,Columbus Crew SC,0,1,1,0,2,1,Nicolai Naess,114295,0
1568,1568,4,5,0,0,0,Houston Dynamo,1,2,6,7,10,5,Tony Cascio,110572,0
1569,1569,0,2,0,0,1,Philadelphia Union,1,7,1,4,2,3,Warren Creavalle,110575,0
1570,1570,4,13,1,8,1,D.C. United,7,12,22,22,28,16,Nick DeLeon,110580,0
1571,1571,2,6,2,10,3,Minnesota United FC,7,8,9,38,24,18,Ethan Finlay,110583,0
1572,1572,0,0,0,0,0,LA Galaxy,0,0,0,0,0,0,Jaime Penedo,28665,0
1573,1573,0,0,0,0,0,LA Galaxy,1,0,0,1,0,1,Rafael Garcia,110586,0
1574,1574,1,2,0,0,0,San Jose Earthquakes,0,0,0,1,0,0,Sam Garza,110587,0
1575,1575,0,0,0,0,0,LA Galaxy,0,0,0,1,0,1,Bryan Gaul,110588,0
1576,1576,0,1,0,1,0,Columbus Crew SC,0,1,2,0,0,1,Kevan George,110589,0
1577,1577,0,0,0,0,0,Atlanta United FC,0,0,0,0,0,0,Paul Christensen,442453,0